version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    # Labels on pull requests for version updates
    labels:
      - "dependencies"
      - "npm"
      - "automerge"
    # Specify target branch
    target-branch: "main"
    # Set reviewers
    reviewers:
      - "project-maintainers"
    # Group dependencies together
    groups:
      dev-dependencies:
        patterns:
          - "@types/*"
          - "eslint*"
          - "jest*"
          - "ts-*"
        update-types:
          - "minor"
          - "patch"
    # Configure commit message
    commit-message:
      prefix: "chore"
      prefix-development: "chore(dev)"
      include: "scope"
    # Set version strategy
    versioning-strategy: increase
    # Configure pull request limits
    open-pull-requests-limit: 10

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    labels:
      - "dependencies"
      - "github-actions"
      - "automerge"
    commit-message:
      prefix: "ci"
      include: "scope"
