apiVersion: v1
kind: Namespace
metadata:
  name: audio-learning-hub
  labels:
    name: audio-learning-hub
    environment: ${ENVIRONMENT}
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: audio-learning-hub-quota
  namespace: audio-learning-hub
spec:
  hard:
    # Compute resources
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi

    # Storage resources
    requests.storage: 100Gi

    # Object count limits
    pods: "20"
    services: "10"
    configmaps: "20"
    secrets: "20"
    persistentvolumeclaims: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: audio-learning-hub-limits
  namespace: audio-learning-hub
spec:
  limits:
  - type: Container
    default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    max:
      cpu: 2000m
      memory: 2Gi
    min:
      cpu: 50m
      memory: 64Mi
