apiVersion: v1
kind: Secret
metadata:
  name: audio-learning-hub-secrets
  labels:
    app: audio-learning-hub
type: Opaque
# Note: In a real environment, these values should be base64 encoded
# and not stored in version control. This is just a template.
# Use kubectl create secret or a secrets management solution like
# Sealed Secrets, Vault, or cloud provider secret management.
stringData:
  # API keys and authentication
  API_KEY: "${API_KEY}"
  JWT_SECRET: "${JWT_SECRET}"

  # Database credentials
  DB_HOST: "${DB_HOST}"
  DB_PORT: "${DB_PORT}"
  DB_NAME: "${DB_NAME}"
  DB_USER: "${DB_USER}"
  DB_PASSWORD: "${DB_PASSWORD}"

  # External service credentials
  AUDIO_SERVICE_API_KEY: "${AUDIO_SERVICE_API_KEY}"
  ML_SERVICE_API_KEY: "${ML_SERVICE_API_KEY}"

  # OAuth credentials
  OAUTH_CLIENT_ID: "${OAUTH_CLIENT_ID}"
  OAUTH_CLIENT_SECRET: "${OAUTH_CLIENT_SECRET}"

  # Encryption keys
  ENCRYPTION_KEY: "${ENCRYPTION_KEY}"
---
# Example of using external secrets manager (AWS Secrets Manager)
# Requires external-secrets operator to be installed
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: audio-learning-hub-external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: audio-learning-hub-secrets
    creationPolicy: Owner
  data:
  - secretKey: API_KEY
    remoteRef:
      key: audio-learning-hub/api-key
  - secretKey: JWT_SECRET
    remoteRef:
      key: audio-learning-hub/jwt-secret
  - secretKey: DB_PASSWORD
    remoteRef:
      key: audio-learning-hub/db-password
  # Add other secrets as needed
