apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audio-learning-hub-data-pvc
  labels:
    app: audio-learning-hub
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
---
# For environments that need to define the storage class explicitly
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: audio-learning-hub-storage
  labels:
    app: audio-learning-hub
provisioner: kubernetes.io/aws-ebs  # Change based on your cloud provider
parameters:
  type: gp2
  fsType: ext4
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
